import './globals.css'

import type { Metadata } from 'next'
import { Roboto, Roboto_Mono } from 'next/font/google'

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--roboto-sans'
})

const robotoMono = Roboto_Mono({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--roboto-mono'
})

export const metadata: Metadata = {
  title: 'Brenno Fruhauf',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${robotoMono.variable}`}>
        {children}
      </body>
    </html>
  )
}
